Create patch set 2
Uploaded patch set 2: New patch set was added with same tree, parent, and commit message as Patch Set 1.

Patch-set: 2
Subject: Fix NoSuchMethodError for getTypeInfo()
Commit: 3dc180cca2f86756e0e45c66affe41e37ff3b67f
Tag: autogenerated:gerrit:newPatchSet
Groups: 0ca5c1964c49475a6616f8e73c1aea30aea175b2